# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Code_For_Good' do
    pod 'AFNetworking'
    pod 'Firebase', '>= 2.5.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'BDBOAuth1Manager'
end

